name: Fetch Cloud Updates

on:
  schedule:
    - cron: '0 6 * * *' # Runs daily at 6 AM UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  fetch-updates:
    runs-on: ubuntu-latest

    permissions:
      contents: write # Allow writing to the repository

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch full history to avoid shallow clone issues

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install feedparser

      - name: Fetch Cloud Updates
        run: python scripts/fetch_cloud_updates.py

      - name: Force Sync and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git fetch origin main # Ensure we have the latest updates
          git reset --hard origin/main # Reset local branch to match the remote
          git add cloud-updates.md
          git commit -m "Update Cloud Updates [skip ci]" || echo "No changes to commit"
          git push --force origin main # Force push to ensure sync
